type: object
properties:
  id:
    type: string
    format: uuid
    example: 38EF63D0-4744-11E4-B3CF-842B2B6CFE1B
  name:
    type: integer
    example: Material Design Icons
  width:
    type: integer
    example: 24
  height:
    type: integer
    example: 24
  fonts:
    type: array
    items:
      $ref: '#/api/model/font'
  icons:
    type: array
    items:
      $ref: '#/api/model/icon'