name: CD

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Store SSH Keys
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa_deploy
        sudo chmod 600 ~/.ssh/id_rsa_deploy
        ssh-keyscan -H "$HOST" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        HOST: ${{ secrets.SSH_SERVER }}
    - name: Install Dependencies
      run: npm install
    - name: Build admin for Production
      run: npm run build
    - name: Build site for Production
      run:  npm run build:site
    - name: Cleanup
      run: |
        ssh ${{ secrets.FTP_USERNAME }}@${{ secrets.SSH_SERVER }} -i ~/.ssh/id_rsa_deploy 'find ${{ secrets.REMOTE_DIR }} -maxdepth 1 -name "*.css" -type f -exec rm -rf {} \;find ${{ secrets.REMOTE_DIR }} -maxdepth 1 -name "*.js" -type f -exec rm -rf {} \;'
    - name: Sync Files
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr
        path: dist/
        remote_path: ${{ secrets.REMOTE_DIR }}
        remote_host: ${{ secrets.SSH_SERVER }}
        remote_user: ${{ secrets.FTP_USERNAME }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
    - name: Trigger Server Steps
      uses: swinton/httpie.action@69125d73caa2c6821f6a41a86112777a37adc171
      with:
        args: POST https://dev.materialdesignicons.com/api/admin/build
